name: Zip Files

on:
  push:
    branches:
      - dev-yasmin

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip files
      run: |
        # Go to the directory containing the files
        cd AWS-ESP-demo
      
        # Zip the files
        zip -r ESP-demo.zip service_files lambda_function.py

